### ISSUE TITLE
[Thermal Foundation x Tinker's Construct] Tools with TF heads can't be repaired

### ISSUE THREAD

**Issue by Revemohl** [CoFH/Feedback#15]
This has been the case ever since the new parts were added.
Any tool with a head made of a Thermal Foundation material (lead, platinum, electrum, invar, etc) can't be repaired at all when placed in a tool station/forge together with an ingot of its corresponding material (the output slot goes blank as soon as you place the ingot in one of the left slots).

Versions:
CoFHCore-[1.7.10]3.0.0B9-89.jar
CoFHLib-[1.7.10]1.0.0B9-60.jar
ThermalExpansion-[1.7.10]4.0.0B8-23.jar
ThermalFoundation-[1.7.10]1.0.0RC1-20.jar
Mantle-1.7.10-0.3.2.jar
TConstruct-1.7.10-1.8.2a.jar

**Comment by skyboy** [comment]
Fixed in dev.

**Comment by mainframecn** [comment]
It is most definitely not fixed, not even in newer releases.

**Comment by Dustmuz** [comment]
i got the exact same problem.. 
even tried a iron only pick, couldn't repair that either.. 
im using TC 1.8.2a.
so fixed?? nah not yet :) 
hope it will be soon though

**Comment by skyboy** [comment]
Not being able to repair iron tools would be a bug with tcon, not TE.
