### ISSUE TITLE
[Thermal Dynamics & Expansion] NPE on Server

### ISSUE THREAD

**Issue by GustoniaEagle** [CoFH/Feedback#291]
See: http://pastebin.com/C0Jmj4Tf
Causing crash on player joining the server.

**Comment by KingLemming** [comment]
Do you have Player Interfaces?

**Comment by GustoniaEagle** [comment]
What do you mean by player interfaces? Such as?

**Comment by KingLemming** [comment]
It's a block called a Player Interface.

Mentioned in #286

**Comment by GustoniaEagle** [comment]
Nobody is using a Player Interface block (Random Things isn't installed).

**Comment by GustoniaEagle** [comment]
The most likely cause of this crash might be a Frame Quarry (Funky Locomotion, latest version) containing 72 servos, 3 retrievers and a few filters as well as hundreds of Warp and Impulse itemducts and Redstone Energy Fluxducts and 2 Tesseracts.

**Comment by KingLemming** [comment]
Is this fixed with the latest releases? I think it might be.

**Comment by GustoniaEagle** [comment]
Not fixed. Still crashing. Log: http://pastebin.com/JXGpEe2N

**Comment by KingLemming** [comment]
Looking at it, I think your world has somehow gotten itself into an invalid state. That's literally a Null Pointer Error after a null check.

**Comment by maruohon** [comment]
Here is a test case for this crash, in case someone wants to take a look at it:
http://pena2.dy.fi/temp/minecraft/TD_crash/

That world contains one region file where the problem occurs. Interestingly, removing AE2 allows the world to load, as does removing that one erroring Pulverizer, which are connected to the same item duct network.

**Comment by Tarig0** [comment]
I am also affected with this crash it seems, this time single player.

**Comment by GustoniaEagle** [comment]
That's a good point actually, we managed to recreate this crash on Single player and Multiplayer, see masa's comment above.

**Comment by Tarig0** [comment]
Could the inventory be being passed as null?

this is where a null could happen
https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/lib/util/helpers/InventoryHelper.java#L200

**Comment by KingLemming** [comment]
Oh I'm exactly aware of where that could be. Thing is, the inventory is checked to exist before that point in the TD code.

**Comment by Tarig0** [comment]
hmm, best to add a null check in the lib anyways? even if TD has the correct checks can't assume other modders will.

**Comment by KingLemming** [comment]
It crossed my mind, though it'll slow things down.

**Comment by Tarig0** [comment]
would instanceof IIventory be faster?

that'll basically be a null check

**Comment by KingLemming** [comment]
No, instanceof is actually slower.

**Comment by Tarig0** [comment]
Since I can't see the TD code. 

Speaking from a player point of view I would rather have a slow down than a re-occurring crash

**Comment by KingLemming** [comment]
I can understand that, although we're talking about a non-deterministic error, which is *really* bad. Covering it up is something, but the inventory shouldn't toggle to null in the first place.

**Comment by Tarig0** [comment]
could a try catch be a good alternative, I understand the exception would cause a larger slow down in these strange cases but, if I understand try catches, it should only slow down these cases.

**Comment by KingLemming** [comment]
Sanity check is in.
