### ISSUE TITLE
[1.11.2] Thermal Foundation: Crash with latest Forge

### ISSUE THREAD

**Issue by Leo40Git** [CoFH/Feedback#312]
A lot of other mods are also installed, but they don't seem to be related to this crash.
Forge version is 1.11.2-13.20.1.2388.
Crash log (fml-client-latest.log): [Thermal_Foundation_latest_Forge_crash.txt](https://github.com/CoFH/Feedback/files/1111202/Thermal_Foundation_latest_Forge_crash.txt)

**Comment by KingLemming** [comment]
Ah yes. Forge finally got around to fixing a bug and now broke my mobs. Fixed in dev, but for now just disable the mobs in config.

**Comment by AfterRebelion** [comment]
How do you disable mobs? I tried changing B:Enable=true to false in config/cofh/thermalfoundation/common.cfg for every of the 3 mobs (Blizz, Blitz and Basalz), but the crash still happens.

**Comment by KingLemming** [comment]
That's exactly how it's done. Unsure why that isn't working.

If that's the case though, downgrade Forge. I won't have a fix pushed for a while, sorry.

**Comment by cursinorock** [comment]
But Vampirism requires the latest forge version to work ç.ç
I like both mods so much ;(

**Comment by KingLemming** [comment]
I have a job, and the mods have a lot of pending changes. So I have to go through and comment out a bunch of stuff all because Forge broke-fixed something.

**Comment by cursinorock** [comment]
I like both mods so much D:

**Comment by cursinorock** [comment]
I understand, sorry to bother D:

**Comment by AfterRebelion** [comment]
Well, I know why it doesn't work to disable it in config, at least.
On [the lastest released build, in the blizz mob](https://github.com/CoFH/ThermalFoundation/blob/c5eeef93aac302691f4514f216e4b3488dc08d20/src/main/java/cofh/thermalfoundation/entity/monster/EntityBlizz.java#L59url) the enable is below the inizialization progress, unlike the rest of the mobs.
On [this commit](https://github.com/CoFH/ThermalFoundation/commit/60fc4c970e74c48cfad07b192d9134a65283b65a#diff-a7c88dd1b7df28866d34c0fa7041404fR43) this was fixed, but the changes there hasn't come into a build yet.
So to have a working "hotfix" for now, I would suggest to make a build now with at least this changes.

**Comment by KingLemming** [comment]
I'll fix it after work.
