### ISSUE TITLE
Thermal Dynamics Crash

### ISSUE THREAD

**Issue by ariosos** [CoFH/Feedback#313]
Got this crash when testing the impulse itemducts (happened initially in the default RC1 version, then I upgraded). My setup was a chest with a resonant retriever pulling items (ore berry bushes) round-robin from several chests (creative chests for testing). I can't seem to reproduce this, though. What happened is that I broke the itemduct between the source and destination chests. I can no longer open my test world unless I remove the mod, and I can open the save. However, if I re-add the mod, the game crashes, even if I replace where the itemducts were with another block (hoping to reset the Minecraft save file data).

FTBInfinity, plus the latest TE files from a few days ago (Yes, I finally found them. :p)

ThermalDynamics-[1.7.10]1.0.0RC7-98

http://pastebin.com/1TukPLkG

**Comment by smit1562** [comment]
i can second this. though i am not so certain it is caused by the resonant retriever in my case.
my server just hangs indefinetly and produces no crash log. i only know that the problem is fixed by removing thermal dynamics and reinstalling after the server started up one time.

also my problems started while i wasnt working on my ducts for hours as i was building something. the connection just timed out and no server restart could ever fix the hanging server. side note, the server hang only starts after it has fully loaded the world.

version thermal dynamics 1.0.0RC2-77 (as is included in FTBinfinity 1.2.1)

**Comment by Iskandra** [comment]
I'm unsure whether this is the same issue, but it's related enough that this stood out as the right place to put it. I'm new to the whole reporting bugs thing, so let me know if I've done anything wrong.

My game crashes when I try to feed items into an itemduct that has a reinforced filter that goes into a TE machine's blank side. The connection between the itemduct and the machine exists when the machine is set to a colour (in which case the set-up is fine), and doesn't exist if the machine's side is blank, unless there's a filter between them. The crash happens no matter whether the items are being pushed out by an MFR grinder, or out of an inventory by a servo. It happens immediately if items are put into the bad set-up, or following the creation of the set-up, if the items were waiting to be pushed out. The game will crash immediately on attempts to start-up a crashed world.

I am using:

 - CofHCore- [1.7.10]3.0.0RC7-211
 - ThermalDynamics-[1.7.10]1.0.0RC7-98
 - ThermalExpansion-[1.7.10]4.0.0RC7-141
 - ThermalFoundation-[1.7.10]1.0.0RC7-62

I am not using a pack, and my complete mod list is below:

http://pastebin.com/dLL4vpw7

My crash report (below) references a setup I had with an MFR grinder, but I duplicated the problem with other set-ups.

http://pastebin.com/jAVE1Bzn

**Comment by KingLemming** [comment]
@smit1562 - that issue has been fixed; you're on a comparatively ancient version of the mod.

@Iskandra - this helps a lot. Thanks, we've been unable to reproduce so far

**Comment by KingLemming** [comment]
I'll be honest, we never did reproduce this properly, but I'm pretty sure it's fixed with RC8 of TD. Closing it down.

**Comment by jmfe10** [comment]
My game crashes when i place down a duct. I'm using RC8 but still crashes.

Here's the crash log: http://pastebin.com/G2uQCF7f
