### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by Jomik1** [CoFH/Feedback#420]
Seem to crash when loading into a server... This is happening on my GF's account, when trying to connect to me through LAN.
I'm "BreezerFly", it's getting a null while trying to Tick Entity.
Seems to be Cofhcore?
http://openeye.openmods.info/crashes/f55841abaaba43ce59d75fee4b1d264b

Full log http://pastebin.com/L9yMuUxW

**Comment by KingLemming** [comment]
It's happening in a CoFH class, but it's not really our fault.

It is however, a very bad sign. It means that for whatever reason, a null player is being passed as part of the event. Forge shouldn't allow this to happen, and something is horribly wrong with your setup if this is occurring.

Does it happen every time?

Also, do you have Fastcraft installed?

**Comment by KingLemming** [comment]
Actually, checking more, this is a vanilla error, which is even worse. It's also *very* strange that we've never seen this before.

**Comment by Jomik1** [comment]
It happens consequently on every run. The setup is -exactly- the same on both computers (I copy pasted .minecraft and checked java versions...) Only difference is one is host, the other is not. I don't have Fastcraft installed.
Should I install that?

**Comment by Jomik1** [comment]
I looked into it some more. And I think NEI has an influence on this... I don't get it unless NEI is installed. NEI gives a NPE with Rendering Screen. I can "fix" that by loading up in SSP before SMP, but doing that gives that null tick. If I don't load SSP first, then I can join the server alright, but the moment I try to open something that has an inventory (activates NEI gui) I crash.

**Comment by Jomik1** [comment]
- This is happening on the client side btw, not on the server (hosting) computer... O.o

**Comment by skyboy** [comment]
Fixed by: https://github.com/CoFH/CoFHCore/commit/539c9b519fa01fe7b0f0bbc52e512251afeaadaf

The NEI error is largely unrelated, but triggers our error. For now, wait until the update information from the CoFH mods has finished displaying when you enter SSP, then go to SMP.

**Comment by Jomik1** [comment]
Thanks! Is it possible to update to to that commit?

**Comment by Jomik1** [comment]
Tested this as I came home. No "update information" appear from CoFHCore, I don't have other mods from Team CoFH installed at this moment. I still get the error. I let it sit in SSP for about a minute before trying to join the SMP. Same crash.
