### ISSUE TITLE
CoFHTweaks: really derpy chunk rendering

### ISSUE THREAD

**Issue by Barhandar** [CoFH/Feedback#483]
While "chunks unrender when you're looking in the other direction" is presumably "1.8 style occlusion" (does it really add FPS to have chunks re-render every time player turns?), the rendering is glitching.

* Chunks render in reverse. Furthest render first, closest last - interaction while not rendered is still possible, they're just not visible. Same happens with the occlusion, just much faster - they flash in a single motion furthest to closest instead of really slowly loading up.
* [Chunks render halfway or not render at all a lot of the time when loading](http://imgur.com/a/Aohtq). 

CoFHCore-[1.7.10]3.0.1-254, CoFHTweaks-[1.7.10]0.1.0B1-23.

**Comment by KingLemming** [comment]
It really does add FPS, yes. The alternative is that they constantly render anyways rather than you know, only the ones you see.

Anyways, paging @skyboy since we aren't seeing this. :/

**Comment by Evolution0** [comment]
If I remember correctly the reverse loading can happen with or without CoFHTweaks, its just a matter of moving around fast enough to make the occlusion glitch and have near chunks get "stuck". Possibly CoFHTweaks more aggressive occlusion is just making this behavior more apparent?

**Comment by TheQuantumGeneral** [comment]
Getting this as well. Hardly moving around at all, on top of reverse chunk loading a lot of blocks stopped updating ie break a block and it looks like its still there. 

Heres an example of both the chunk rendering and ghost block issues
http://i.imgur.com/LJ3qxlt.png

**Comment by MrLavender** [comment]
Also seeing this.

Macbook Pro Late 2013 (i7-4960HQ, 16GB, Nvidia 750M)
OSX 10.10 + Java 1.8.0_45
COFHtweaks 0.1.0B1-24

I don't use optifine, fpsplus, etc. Removed fastcraft while testing COFHtweaks.

- Should be a wall here: https://i.imgur.com/rgHZjln.png

- Should be a hill here: https://i.imgur.com/pgVVYGc.png

- Things 'pop' into view when I turn around quickly, this just looks horrible

- Doors render as closed even when open (they're Carpenters Blocks doors if it makes a difference)

Very nice performance boost though, if the rendering bugs can be squashed (80-100 fps with fastcraft, 120-140 with COFHtweaks).

**Comment by skyboy** [comment]
Most of these should be corrected now (except the caprenter's blocks thing? dunno what's up with that.).

**Comment by MrLavender** [comment]
Just tried CoFHTweaks-[1.7.10]0.1.0B2-30. It's better (and doors render correctly now) but I'm still seeing some problems. Mostly happens when outside, standing in one place and looking around things occasionally disappear.

https://imgur.com/a/2t9Jn

Inside or underground the only glitch I've seen is the last image in that album.

**Comment by KamiKazeKenji** [comment]
I'm still getting the same issues on 0.1.0B2-30. 

http://imgur.com/a/dCJLZ

Chunks keep flickering, and it's really annoying. This strange behavior seems similar to what happens with multi threaded versions of Optifine with Threaded Optimization not turned off in the Nvidia control panel.

**Comment by skyboy** [comment]
These issues (including chunks re-rendering when you turn around) should be resolved now. Occasionally chunks that fail to render at all, or flicker when you look around will happen, but this is beyond my control: they're a result of fundamental problems in minecraft 1.7 and below (there are several videos that shows things similar to @KamiKazeKenji's album in vanilla minecraft)
