### ISSUE TITLE
[MFR] Harvester crash when BC pipe connected to wrong side

### ISSUE THREAD

**Issue by TehStoneMan** [CoFH/Feedback#716]
Connecting a Buildcraft transport pipe to any side of a harvester other than the output side crashes the server.
Connecting the pipe to the correct output side of the harvester works fine, as expected.

**Comment by KingLemming** [comment]
...have a crash log?

**Comment by TehStoneMan** [comment]
Crash log
````
[09:24:42] [main/INFO]: Setting user: TehStoneMan
[09:24:43] [Client thread/INFO]: LWJGL Version: 2.9.1
[09:24:57] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:AgriCraft, FMLFileResourcePack:Applied Energistics 2, FMLFileResourcePack:BetterStorage, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:BiblioWoods Biomes O'Plenty Edition, FMLFileResourcePack:BiblioWoods Forestry Edition, FMLFileResourcePack:Big Reactors, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:Botania, FMLFileResourcePack:BC Factory, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:Carpenter's Blocks, FMLFileResourcePack:Chisel 2, FMLFileResourcePack:CTMLib, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:EnhancedPortals, FMLFileResourcePack:Extra Cells 2, FMLFileResourcePack:Forestry for Minecraft, FMLFileResourcePack:Galacticraft Planets, FMLFileResourcePack:Galacticraft Core, FMLFileResourcePack:Immibis Core, FMLFileResourcePack:JABBA, FMLFileResourcePack:Mantle, FMLFileResourcePack:Mekanism, FMLFileResourcePack:MekanismGenerators, FMLFileResourcePack:MekanismTools, FMLFileResourcePack:MineFactory Reloaded, FMLFileResourcePack:MFR Compat: Applied Energistics, FMLFileResourcePack:MFR Compat: Atum, FMLFileResourcePack:MFR Compat: BackTools, FMLFileResourcePack:MFR Compat: BuildCraft, FMLFileResourcePack:MFR Compat: Chococraft, FMLFileResourcePack:MFR Compat: ExtraBiomes, FMLFileResourcePack:MFR Compat: Forestry, FMLFileResourcePack:MFR Compat: ForgeMicroblock, FMLFileResourcePack:MFR Compat: IC2, FMLFileResourcePack:MFR Compat: Mystcraft, FMLFileResourcePack:MFR Compat ProjectRed, FMLFileResourcePack:MFR Compat: Railcraft, FMLFileResourcePack:MFR Compat: Sufficient Biomes, FMLFileResourcePack:MFR Compat: Thaumcraft, FMLFileResourcePack:MFR Compat: Thermal Expansion, FMLFileResourcePack:MFR Compat: Tinkers' Construct, FMLFileResourcePack:MFR Compat: TwilightForest, FMLFileResourcePack:MFR Compat: Vanilla, FMLFileResourcePack:Necromancy, FMLFileResourcePack:NotEnoughKEys, FMLFileResourcePack:MapWriter, FMLFileResourcePack:Opis, FMLFileResourcePack:Pam's HarvestCraft, FMLFileResourcePack:RedLogic, FMLFileResourcePack:Roguelike Dungeons, FMLFileResourcePack:Tinkers' Construct, FMLFileResourcePack:Thaumcraft, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:Witchery, FMLFileResourcePack:Baubles, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin
[09:25:13] [Sound Library Loader/INFO]: Sound engine started
[09:25:21] [Client thread/INFO]: Created: 16x16 textures/blocks-atlas
[09:25:21] [Client thread/INFO]: Created: 16x16 textures/items-atlas
[09:25:35] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:AgriCraft, FMLFileResourcePack:Applied Energistics 2, FMLFileResourcePack:BetterStorage, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:BiblioWoods Biomes O'Plenty Edition, FMLFileResourcePack:BiblioWoods Forestry Edition, FMLFileResourcePack:Big Reactors, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:Botania, FMLFileResourcePack:BC Factory, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:Carpenter's Blocks, FMLFileResourcePack:Chisel 2, FMLFileResourcePack:CTMLib, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:EnhancedPortals, FMLFileResourcePack:Extra Cells 2, FMLFileResourcePack:Forestry for Minecraft, FMLFileResourcePack:Galacticraft Planets, FMLFileResourcePack:Galacticraft Core, FMLFileResourcePack:Immibis Core, FMLFileResourcePack:JABBA, FMLFileResourcePack:Mantle, FMLFileResourcePack:Mekanism, FMLFileResourcePack:MekanismGenerators, FMLFileResourcePack:MekanismTools, FMLFileResourcePack:MineFactory Reloaded, FMLFileResourcePack:MFR Compat: Applied Energistics, FMLFileResourcePack:MFR Compat: Atum, FMLFileResourcePack:MFR Compat: BackTools, FMLFileResourcePack:MFR Compat: BuildCraft, FMLFileResourcePack:MFR Compat: Chococraft, FMLFileResourcePack:MFR Compat: ExtraBiomes, FMLFileResourcePack:MFR Compat: Forestry, FMLFileResourcePack:MFR Compat: ForgeMicroblock, FMLFileResourcePack:MFR Compat: IC2, FMLFileResourcePack:MFR Compat: Mystcraft, FMLFileResourcePack:MFR Compat ProjectRed, FMLFileResourcePack:MFR Compat: Railcraft, FMLFileResourcePack:MFR Compat: Sufficient Biomes, FMLFileResourcePack:MFR Compat: Thaumcraft, FMLFileResourcePack:MFR Compat: Thermal Expansion, FMLFileResourcePack:MFR Compat: Tinkers' Construct, FMLFileResourcePack:MFR Compat: TwilightForest, FMLFileResourcePack:MFR Compat: Vanilla, FMLFileResourcePack:Necromancy, FMLFileResourcePack:NotEnoughKEys, FMLFileResourcePack:MapWriter, FMLFileResourcePack:Opis, FMLFileResourcePack:Pam's HarvestCraft, FMLFileResourcePack:RedLogic, FMLFileResourcePack:Roguelike Dungeons, FMLFileResourcePack:Tinkers' Construct, FMLFileResourcePack:Thaumcraft, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:Witchery, FMLFileResourcePack:Baubles, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin, FMLFileResourcePack:Carpenter's Blocks Cached Resources
[09:25:42] [Client thread/INFO]: Created: 2048x2048 textures/blocks-atlas
[09:25:44] [Client thread/INFO]: Created: 2048x2048 textures/items-atlas
[09:25:45] [Sound Library Loader/INFO]: Sound engine started
[09:26:16] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[09:26:16] [Server thread/INFO]: Generating keypair
[09:26:17] [Server thread/INFO]: Preparing start region for level 0
[09:26:19] [Server thread/INFO]: Changing view distance to 12, from 10
[09:26:19] [Server thread/INFO]: TehStoneMan[local:E:e2c482d1] logged in with entity id 426 at (-730.2389630507379, 70.0, -287.07499998807907)
[09:26:19] [Server thread/INFO]: TehStoneMan joined the game
[09:26:26] [Client thread/INFO]: [CHAT] botania.versioning.flavour39
[09:26:26] [Client thread/INFO]: [CHAT] You are running Botania build 201, the latest is build 203.
[09:26:26] [Client thread/INFO]: [CHAT] Click for... [Download] [Website] [Changelog]
[09:26:27] [Client thread/INFO]: [CHAT] §6The mod Extra Cells 2 is supporting In-Game Wiki mod. §6However, In-Game Wiki isn't installed! [Download Latest]
[09:32:34] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.NullPointerException
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStackInAir(UtilInventory.java:388) ~[UtilInventory.class:?]
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStackInAir(UtilInventory.java:326) ~[UtilInventory.class:?]
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStackInAir(UtilInventory.java:322) ~[UtilInventory.class:?]
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStack(UtilInventory.java:277) ~[UtilInventory.class:?]
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStack(UtilInventory.java:219) ~[UtilInventory.class:?]
	at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryInventory.doDrop(TileEntityFactoryInventory.java:255) ~[TileEntityFactoryInventory.class:?]
	at powercrystals.minefactoryreloaded.tile.machine.TileEntityHarvester.activateMachine(TileEntityHarvester.java:199) ~[TileEntityHarvester.class:?]
	at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.func_145845_h(TileEntityFactoryPowered.java:109) ~[TileEntityFactoryPowered.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
	... 4 more
[09:32:34] [Server thread/ERROR]: This crash report has been saved to: C:\Minecraft Games\Stoney Craft\crash-reports\crash-2015-07-20_09.32.34-server.txt
[09:32:34] [Server thread/INFO]: Stopping server
[09:32:34] [Server thread/INFO]: Saving players
[09:32:34] [Server thread/INFO]: Saving worlds
[09:32:34] [Server thread/INFO]: Saving chunks for level 'Test World'/Overworld
[09:32:34] [Server thread/INFO]: Saving chunks for level 'Test World'/Nether
[09:32:34] [Server thread/INFO]: Saving chunks for level 'Test World'/The End
[09:32:34] [Server thread/INFO]: Saving chunks for level 'Test World'/Spirit World
[09:32:34] [Server thread/INFO]: Saving chunks for level 'Test World'/Torment
[09:32:34] [Server thread/INFO]: Saving chunks for level 'Test World'/Mirror
[09:32:34] [Server thread/INFO]: Saving chunks for level 'Test World'/The Outer Lands
````

**Comment by skyboy** [comment]
Fixed in dev

**Comment by Klash2b** [comment]
Hello, i still have the same problem after a friend put a buildcraft pipe to the wrong side of an harvester, you say it's fixed but i have the latest version of minefactoryreloaded & cofhcore, how can i fix this?

Thanks.
