### ISSUE TITLE
Cache from thermal expansion cause render bug.

### ISSUE THREAD

**Issue by marcin212** [CoFH/Feedback#9]
before placing: https://dl.dropboxusercontent.com/u/25172450/8388e2a2122208a0dbd6ae6af0cc1a48.png

after placing:
https://dl.dropboxusercontent.com/u/25172450/Zrzut%20ekranu%202015-01-07%2001.00.57.png

CoFHCore-[1.7.10]3.0.0B9-73
CoFHCore-[1.7.10]3.0.0B9-73
ThermalExpansion-[1.7.10]4.0.0B8-23
forge: 1.7.10-10.13.2.1284

**Comment by KingLemming** [comment]
I don't see any cache in that picture. You also haven't included a modlist.

**Comment by KevinsCode** [comment]
Marcin, it'll most likely be not a TE thing and a BC bug with rendering

**Comment by marcin212** [comment]
video: https://www.youtube.com/watch?v=wSGq81j1viM
The error occurs also on other items.

I placed cache.
Error appears after re-login:(screen) https://dl.dropboxusercontent.com/u/25172450/bugs/3f419c18f80ef83846a822fe14875e3f.png

Modlist: http://pastebin.com/5Q88mMKQ

**Comment by KevinsCode** [comment]
Is this a custom made modpack or a Pre Made one such as FTB?

**Comment by marcin212** [comment]
custom

**Comment by KevinsCode** [comment]
Your issue is probably a config/mod compatibilty error with other mods then, i've tested it out just now and it works fine for me, might also be a graphics card thing

**Comment by KevinsCode** [comment]
try find out which mod is causing the error because it works fine on my custom pack

**Comment by KevinsCode** [comment]
might also be something else in your area causing the problem

**Comment by Kubuxu** [comment]
@KevinsCode I talked about it with @skyboy. He told me that it is a bug in CoFHCore and is fixed in dev version. Also it is random as it depends on sorting of rendering.

**Comment by marcin212** [comment]
I create flat world.
 https://dl.dropboxusercontent.com/u/25172450/bugs/6934a058d80c1dbe11cd804fad38f7d0.png

**Comment by eXiGe** [comment]
I can confirm this is happening to me as well. Using CofhCore which released today, though it has been around awhile. I had assumed it was fastcraft, but it still persisted with fastcraft removed. After reading this I tested it a bit, and while random like Kubuxu said, the issue always went away when the cache's were picked up / removed.

For me it effects the 3d rendering of 2d sprites used by blocks, i.e. Ender IO killer joe's weapon, Experience Obelisk xp rod, ComputerCraft turtle tools etc. Also rendering for killer joe and the casts when placed in a casting table for Tinker's Construct.

I don't know if the dev version Kubuxu referenced has been released, but as initially stated, I am using the current CofhCore version.

**Comment by Kubuxu** [comment]
@eXiGe I just were told it is fixed. It might be just for me to give up and leave it. Problem is in Item rendering function in CoFHCore where blending function is being changed and not restored.

**Comment by eXiGe** [comment]
Just took the time to do a bit more testing on this, and I have narrowed it down quite a bit to where it is consistently reproducible.

Mod list:
CodeChickenCore-1.7.10-1.0.4.35-universal
CodeChickenLib-1.7.10-1.1.1.99-universal
CoFHCore-[1.7.10]3.0.0B9-96
CoFHLib-[1.7.10]1.0.0B9-64
EnderIO-1.7.10-2.2.6.317
Mantle-1.7.10-0.3.2
NotEnoughItems-1.7.10-1.0.4.83-universal
TConstruct-1.7.10-1.8.2a
ThermalExpansion-[1.7.10]4.0.0B8-23
ThermalFoundation-[1.7.10]1.0.0RC1-27

http://imgur.com/a/uoE9G

To reproduce:
Place cache
Place affected block(s) , i.e. casting table with cast, killer joe etc
Place normal item in cache, itemblocks don't cause the error? - this step can proceed the 2nd as long as the cache is placed before the affected blocks

To clear:
Removing items will temporarily clear the error on affected blocks until you return the items
Removing the cache will clear it semi permanently until the affected blocks are picked up and placed again after the cache is placed again

@Kubuxu hopefully this will give them enough info to fix it...

**Comment by bochen415** [comment]
I can confirm this in my setup with some of EnderIO blocks and the Tcon casting table

**Comment by skyboy** [comment]
Is this still an issue with the latest alpha of CoFHCore?

**Comment by marcin212** [comment]
as before http://i.gyazo.com/474d24c56419a3e8590b1cd90bbd3fc4.png
CoFHCore-[1.7.10]3.0.0B9-99
CoFHLib-[1.7.10]1.0.0B9-65

**Comment by eXiGe** [comment]
It renders differently now but still with errors. The blocks with the visible errors were placed after the cache was placed. http://imgur.com/a/4viUK

**Comment by skyboy** [comment]
Appears to be resolved in dev.

**Comment by eXiGe** [comment]
I can see why you have the "Probably Fixed" tag now, cause you really don't know. Should have used it here.

In case you are confused, it isn't fixed in the new versions released yesterday.
