### ISSUE TITLE
[CoFHTweaks] Strange checkboard pattern of missing rendered chunks

### ISSUE THREAD

**Issue by OreCruncher** [CoFH/Feedback#922]
CoFHTweaks-[1.7.10]1.0.1-38-dev.jar

![The Problem](https://raw.githubusercontent.com/OreCruncher/Restructured/master/docs/images/2015-11-08_13.08.44.png)

If I hit `F3+A` screen refreshes and things are fine.

**Comment by skyboy** [comment]
This may also be fixed in 1.0.2B1, unsure.

**Comment by OreCruncher** [comment]
I will give it a test in the next day or so and let you know.  Thanks!

**Comment by OreCruncher** [comment]
Well my Minecraft server rebooted so I decided to take a look.  I don't think it's fixed.  Came across a region that I can xray through to see underground, but the blocks are there as the back focus outline for the block shows.  I am using 1.0.2B1-39-dev.jar.

Is there any other information I can give you to help narrow this down?

**Comment by skyboy** [comment]
Fixed in build 40

**Comment by OreCruncher** [comment]
Updated to 2B1-40....

![Hmmm](https://raw.githubusercontent.com/OreCruncher/Restructured/master/docs/images/2015-11-08_21.08.26.png)

**Comment by KingLemming** [comment]
That happens even without tweaks. That's always happened in 1.7.10...

**Comment by skyboy** [comment]
It was tweaks, there's a build 41. It was clogging up its own render pipe.

**Comment by OreCruncher** [comment]
Looks squashed in 41.  Yay!
